# Generated by Django 5.1.6 on 2025-02-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0003_consultas"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultas",
            name="visualizacoes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
